apiVersion: 1
datasources:
  - name: Tacklebox PostgreSQL
    type: grafana-postgresql-datasource
    uid: P8486BE4CAA945761
    url: host.docker.internal:5432
    database: tacklebox
    user: tacklebox
    isDefault: true
    secureJsonData:
      password: tacklebox
    jsonData:
      database: tacklebox
      sslmode: disable
      maxOpenConns: 5
      postgresVersion: 1600
